USE GripItemTrader

IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Person')
BEGIN
	CREATE TABLE [Person](
		[Id]		INT PRIMARY KEY IDENTITY(1,1),
		[Name]		VARCHAR(100) NOT NULL UNIQUE,
		[IsActive]	BIT NOT NULL
	);
END

IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Item')
BEGIN
	CREATE TABLE [Item](
		[Id]		INT PRIMARY KEY IDENTITY(1,1),
		[Name]		VARCHAR(100) NOT NULL UNIQUE,
		[IsActive]	BIT NOT NULL,
		[PersonId]	INT NOT NULL REFERENCES [Person]([Id])
	);
END

IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ItemTransfer')
BEGIN
	CREATE TABLE [ItemTransfer](
		[Id]			INT PRIMARY KEY IDENTITY(1,1),
		[FromPersonId]	INT NOT NULL REFERENCES [Person]([Id]),
		[ToPersonId]	INT NOT NULL REFERENCES [Person]([Id]),
		[ItemId]		INT NOT NULL REFERENCES [Item]([Id])
	);
END
